CarRentalService/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', user_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('customer/<int:customer_id>/', include('customer.urls')), 
    path('rental/', include('rental.urls')), 
    path('register/', user_views.register, name='register'),
    path('employee/', include('employee.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('manager/', include('manager.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path("__reload__/", include("django_browser_reload.urls")), # for auto reloading of the server
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/urls.py
from django.urls import path
from . import views
import uuid

app_name = 'customer'
urlpatterns = [
    path('', views.landingPage, name='landingPage'),
    path('<uuid:vehicle_id>/', views.vehiclePage, name='vehiclePage'),
    path('<uuid:vehicle_id>/submitRental/', views.submitRental, name='submitRental'),
    path('<int:vehicle_id>/viewRental/', views.viewRental, name="viewRental"),
    path('<uuid:vehicle_id>/addBalance/', views.addBalance, name="addBalance"),
    path('addBalanceHome/', views.addBalanceHome, name="addBalanceHome"),
    path('<int:vehicle_id>/<uuid:reservation_id>/cancelBooking/', views.cancelBooking, name="cancelBooking"),
    path('<int:vehicle_id>/<uuid:reservation_id>/requestPickup/', views.requestPickup, name="requestPickup"),

]

rental/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

rental/models.py
from django.db import models

customer/views.py
from datetime import datetime
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from reservation.models import Reservation
from users.models import Profile
from employee.models import Vehicle
from django.contrib.auth.models import User
from datetime import date
from .utils import Calendar
from django.utils.safestring import mark_safe


def landingPage(request, customer_id):
    customerInfo = {
        "id": customer_id, 
        "vehicleInfo": Vehicle.objects.all,
        "reservationList":  Reservation.objects.all,
    }
    return render(request, "customer/index.html", customerInfo)

def buildYear(request, vehicle_id):
    calendarYear = []
    for i in range(1,13):
        calendarYear.append(calendarView(request, vehicle_id, addMonths=i))
    
    return calendarYear


def vehiclePage(request, customer_id, vehicle_id):
    vehicle = Vehicle.objects.get(vehicleID=vehicle_id)
    
    vehicleInfo = { 
        "id": customer_id, 
        "vehicleInfo" : vehicle,  
        "reserved": Reservation.objects.filter(carId=vehicle_id),
        "calendar": buildYear(request, vehicle_id),
    }
    return render(request, "customer/vehicle.html", vehicleInfo)


# Updates reservation object in the database with customer data
# Subtracts total cost from the customer balance
def submitRental(request, customer_id, vehicle_id):
    reservation = Reservation()
    customer = Profile.objects.get(id=customer_id)

    startDate = datetime.strptime(request.POST.get('startDate'), '%Y-%m-%d').date()
    endDate = datetime.strptime(request.POST.get('endDate'), '%Y-%m-%d').date()

    for reserved in Reservation.objects.filter(carId=vehicle_id):
        if reserved.startDate <= startDate <= reserved.endDate or reserved.startDate <= endDate <= reserved.endDate:
            return HttpResponseRedirect(reverse('customer:vehiclePage', args=(customer_id, vehicle_id)))

    pickUpAddress = request.POST.get('pickUpAddress')
    hasInsurance = request.POST.get('hasInsurance', False)
    totalCost = request.POST.get('totalCost')

    if hasInsurance == 'on':
        hasInsurance = True
    else:
        hasInsurance = False

    reservation.carId = vehicle_id
    reservation.userId = customer_id
    reservation.startDate = startDate
    reservation.endDate = endDate
    reservation.pickUpAddress = pickUpAddress
    reservation.needsPickup = False
    reservation.hasInsurance = hasInsurance
    reservation.isReturned = False

    customer.moneyBalance -= int(totalCost)

    reservation.save()
    customer.save()

    return HttpResponseRedirect(reverse('customer:viewRental', args=(customer_id, 0)))


def viewRental(request, customer_id, vehicle_id):
    today = date.today()
    activeReservations = Reservation.objects.filter(userId=customer_id, startDate__lte=today, endDate__gte=today).values()
    pastReservations = Reservation.objects.filter(userId=customer_id, endDate__lt=today).values()
    futureReservations = Reservation.objects.filter(userId=customer_id, startDate__gt=today).values()

    context = {
        "activeReservations": filterReservations(activeReservations),
        "pastReservations": filterReservations(pastReservations),
        "futureReservations": filterReservations(futureReservations),
    }
    return render(request, "customer/rental.html", context)


def filterReservations(reservationObj):
    rentals = []
    reservations = []
    
    for reservation in reservationObj:
        rentals.append(Vehicle.objects.get(vehicleID=reservation.get('carId')))
        reservations.append(reservation)

    return zip(rentals, reservations)


# accesses the customer profile via the customer id and updates the moneyBalance field
# Redirects back to the vehicle page after the balance has been updated in the database
def addBalance(request, customer_id, vehicle_id):
    customer = Profile.objects.get(id=customer_id)

    add = request.POST.get('add')
    addedBalance = customer.moneyBalance + int(add)
    customer.moneyBalance = addedBalance
    customer.save()

    return HttpResponseRedirect(reverse('customer:vehiclePage', args=(customer_id, vehicle_id)))


# I know there has to be a better way of doing this, I just dont feel like doing it that way right now
def addBalanceHome(request, customer_id):
    customer = Profile.objects.get(id=customer_id)

    add = request.POST.get('add')
    addedBalance = customer.moneyBalance + int(add)
    customer.moneyBalance = addedBalance
    customer.save()

    return HttpResponseRedirect(reverse('customer:landingPage', args=(customer_id, )))


def cancelBooking(request, customer_id, vehicle_id, reservation_id):
    reservation = Reservation.objects.get(reservationId=reservation_id)
    reservation.delete()
    return HttpResponseRedirect(reverse('customer:viewRental', args=(customer_id, 0)))


def requestPickup(request, customer_id, vehicle_id, reservation_id):
    reservation = Reservation.objects.get(reservationId=reservation_id)
    pickUpAddress = request.POST.get('pickUpAddress')

    if len(pickUpAddress) > 0:
        reservation.pickUpAddress = pickUpAddress
    
    reservation.needsPickup = True
    reservation.save()
    
    return HttpResponseRedirect(reverse('customer:viewRental', args=(customer_id, 0)))


def calendarView(request, vehicle_id, addMonths=0):
    d = get_date(request.GET.get('day', None))
    cal = Calendar(d.year, d.month)
    html_cal = cal.formatmonth(vehicle_id, addMonths, withyear=True)
    print(html_cal)
    return mark_safe(html_cal)


def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

rental/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
  return HttpResponse("TODO: Landing Page")

customer/templates/customer/rental.html
<!DOCTYPE html>
{% load static tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Rentals</title>
    {% tailwind_css %}
</head>
<body class="bg-secondary text-white-900">
    <nav class="flex items-center justify-between flex-wrap bg-primary p-5">
        <div class="flex items-center flex-shrink-0 text-white mr-6">
            <svg class="fill-current h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
            <span class="font-semibold text-xl tracking-tight">Your Rentals</span>
        </div>    
        <div class="static">
            <img src="{% static 'customer/Images/profile.png' %}" width="40" height="40" class="hover:scale-125 transition-all duration-500" onclick="display('profileMenu')"/>
        </div>
    </nav>

    <div class="fixed top-0 w-full h-full bg-black opacity-50" id="background" style="visibility: hidden;" onclick="remove(event)"></div>
    <div class="bg-primary absolute right-5 mt-5 p-5 text-white rounded-md" id="profileMenu" style="visibility: hidden">
        <p class="text-xl">Your Balance: <span class="float-right font-bold">${{request.user.profile.moneyBalance}}</span></p>
        <div class="flex flex-col items-center justify-center" >
            <button class="bg-purple-900 hover:bg-purple-700 w-52 h-10 mt-5 rounded-md font-semibold">Add To Account</button>
            <a class="bg-purple-900 hover:bg-purple-700 w-52 h-10 mt-5 rounded-md flex flex-col items-center justify-center font-semibold"  href="{% url 'customer:viewRental' request.user.profile.id 0 %}">View Rentals</a>
            <a class="bg-purple-900 hover:bg-purple-700 w-52 h-10 mt-5 rounded-md flex flex-col items-center justify-center font-semibold" href="{% url 'login' %}">Log Out</a>
        </div>
    </div>

    <div class="flex justify-center">
        <h2 class="text-4xl font-semibold mt-20 ">Active Reservations </h2>
    </div>
    {% for rental, reservation in activeReservations %}
        <div class="flex justify-center mt-10 ">
            <div class="flex md:flex-row flex-col bg-primary rounded-md p-5">
                <div class="basis-full">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-auto w-[26rem] sm:h-96 rounded-md">
                </div>
                <div class="w-full basis-1/4 flex md:flex-col flex-row justify-center md:mt-0 mt-10">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-48 md:w-60 w-32 rounded-md md:mb-9 hover:scale-110 transition-all md:mr-0 sm:mr-14 mr-4">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-48 md:w-60 w-32 rounded-md md:mb-9 hover:scale-110 transition-all md:mr-0 sm:mr-12 mr-4">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-48 md:w-60 w-32 rounded-md hover:scale-110 transition-all ">
                </div>
            </div>
        </div> 

        <div class="flex justify-center mb-14">
            <div class="bg-primary md:w-[60rem] sm:w-[45rem] w-[26rem] mt-5 rounded-md">
                <p class="ml-5 mt-4 sm:text-lg text-base"><span class="sm:text-xl text-base font-semibold">{{rental.vehicleYear}} <span>{{rental.vehicleMake}}</span> <span>{{rental.vehicleModel}}</span></span></p>
                <p class="ml-5 mt-2 sm:text-base text-sm"> ${{rental.vehiclePrice}} / Day </p>
                <h2 class="mb-5 ml-5 mt-2">Your booking dates: {{reservation.startDate}}-{{reservation.endDate}}</h2>
                <button onclick="display('confirmAddress')" class="float-right mb-5 mr-5 bg-purple-900 w-52 h-10 rounded-md font-semibold hover:bg-purple-700">Request Maintenance</button>

                <!-- popup for to request pickup -->
                <div class="flex justify-center fixed top-0 left-1/2">
                    <div class="fixed top-1/3 md:w-[30rem] w-96 bg-primary rounded-md p-5" id="confirmAddress" style="visibility: hidden;">
                        <p class="text-lg font-semibold">Your Vehicle Will Be Picked Up And Serviced</p>
                        <br>
                        <br>
                        <p>Please Enter The Current Location Of The Vehicle</p>
                        <form action="{% url 'customer:requestPickup' request.user.profile.id 0 reservation.reservationId %}" method="post">
                            {% csrf_token %}
                            <div class="flex justify-center">
                                <input placeholder="If Blank Original Location Will Be Used" class=" mt-5 w-full rounded-md border-transparent bg-secondary border-2 focus:ring-purple-900 focus:border-purple-900 focus:ring-1" type="text" name="pickUpAddress" id="pickUpAddress" onchange="cal()">
                            </div>
                            <input type="submit" name="requestMaintenance" id="requestMaintenance" value="Request Maintenance" class="float-right mt-10 bg-purple-900 w-52 h-10 hover:bg-purple-700 rounded-md flex flex-col items-center disabled:bg-gray-900 disabled:text-gray-700 justify-center font-semibold">
                        </form>
                    </div>
                </div>

            </div>
        </div>
    {% endfor %}    

    <div class="flex justify-center">
        <h2 class="text-4xl font-semibold mt-6 ">Future Reservations</h2>
    </div>
    {% for rental, reservation in futureReservations %}
        <div class="flex justify-center mt-10 ">
            <div class="flex md:flex-row flex-col bg-primary rounded-md p-5">
                <div class="basis-full">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-auto w-[26rem] sm:h-96 rounded-md">
                </div>
                <div class="w-full basis-1/4 flex md:flex-col flex-row justify-center md:mt-0 mt-10">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-48 md:w-60 w-32 rounded-md md:mb-9 hover:scale-110 transition-all md:mr-0 sm:mr-14 mr-4">
                    <img src="{{rental.vehicleImage2.url}}" class="sm:w-48 md:w-60 w-32 rounded-md md:mb-9 hover:scale-110 transition-all md:mr-0 sm:mr-12 mr-4">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-48 md:w-60 w-32 rounded-md hover:scale-110 transition-all ">
                </div>
            </div>
        </div> 

        <div class="flex justify-center mb-14">
            <div class="bg-primary md:w-[60rem] sm:w-[45rem] w-[26rem] mt-5 rounded-md">
                <p class="ml-5 mt-4 sm:text-lg text-base"><span class="sm:text-xl text-base font-semibold">{{rental.vehicleYear}} <span>{{rental.vehicleMake}}</span> <span>{{rental.vehicleModel}}</span></span></p>
                <p class="ml-5 mt-2 sm:text-base text-sm"> ${{rental.vehiclePrice}} / Day</p>
                <h2 class="mb-5 ml-5 mt-2">Your booking dates: {{reservation.startDate}}-{{reservation.endDate}}</h2>
                <button onclick="display('cancel')" class="float-right mb-5 mr-5 bg-purple-900 w-52 h-10 rounded-md font-semibold hover:bg-purple-700">Cancel Booking</button>

                <!-- popup for to confirm cancellation -->
                <div class="flex justify-center fixed top-0 left-1/2">
                    <div class="fixed top-1/3 md:w-[30rem] w-96 bg-primary rounded-md p-5" id="cancel" style="visibility: hidden;">
                        <p class="text-lg">Are You Sure You Want To Cancel This Booking</p>
                        <p class="text-sm text-gray-400">Your Order Will Not Be Refunded</p>
                        <form action="{% url 'customer:cancelBooking' request.user.profile.id 0 reservation.reservationId %}" method="post">
                            {% csrf_token %}
                            <input type="submit" name="cancel" id="cancel" value="Yes" class="float-right mt-10 bg-purple-900 w-52 h-10 hover:bg-purple-700 rounded-md flex flex-col items-center disabled:bg-gray-900 disabled:text-gray-700 justify-center font-semibold">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}


    <div class="flex justify-center">
        <h2 class="text-4xl font-semibold mt-6 ">Past Reservations</h2>
    </div>
    {% for rental, reservation in pastReservations %}
        <div class="flex justify-center mt-10">
            <div class="flex md:flex-row flex-col bg-primary rounded-md p-5">
                <div class="basis-full">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-auto w-[26rem] sm:h-96 rounded-md">
                </div>
                <div class="w-full basis-1/4 flex md:flex-col flex-row justify-center md:mt-0 mt-10">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-48 md:w-60 w-32 rounded-md md:mb-9 hover:scale-110 transition-all md:mr-0 sm:mr-14 mr-4">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-48 md:w-60 w-32 rounded-md md:mb-9 hover:scale-110 transition-all md:mr-0 sm:mr-12 mr-4">
                    <img src="{{rental.vehicleImage.url}}" class="sm:w-48 md:w-60 w-32 rounded-md hover:scale-110 transition-all ">
                </div>
            </div>
        </div> 

        <div class="flex justify-center mb-14">
            <div class="bg-primary md:w-[60rem] sm:w-[45rem] w-[26rem] mt-5 rounded-md">
                <p class="ml-5 mt-4 sm:text-lg text-base"><span class="sm:text-xl text-base font-semibold">{{rental.vehicleYear}} <span>{{rental.vehicleMake}}</span> <span>{{rental.vehicleModel}}</span></span></p>
                <p class="ml-5 mt-2 sm:text-base text-sm"> ${{rental.vehiclePrice}} / Day </p>
                <h2 class="mb-5 ml-5 mt-2">Your booking dates: {{reservation.startDate}}-{{reservation.endDate}}</h2>
            </div>
        </div>
    {% endfor %}

    <script>
        var profileMenu = document.getElementById('profileMenu');
        var background = document.getElementById('background');
        var cancelPopup = document.getElementById('cancel');
        var confirmAddress = document.getElementById('confirmAddress');

        function display(itemId){
            document.getElementById(itemId).style.visibility = 'visible';
            background.style.visibility = 'visible';
            disableScroll();
        }

        function remove(event){
            event.currentTarget.style.visibility = "hidden";
            profileMenu.style.visibility = "hidden";
            cancelPopup.style.visibility = "hidden";
            confirmAddress.style.visibility = "hidden";
            enableScroll();
        }

        /**
         * Disables scrolling on the current page by preventing the default 
         * behavior of the mouse wheel and touch events.
         */
        function disableScroll() {
            document.body.style.overflow = "hidden";
            document.addEventListener("touchmove", preventDefault, { passive: false });
            document.addEventListener("wheel", preventDefault, { passive: false });
        }

        /**
         * Enables scrolling on the current page by restoring the default behavior 
         * of the mouse wheel and touch events.
         */
        function enableScroll() {
            document.body.style.overflow = "auto";
            document.removeEventListener("touchmove", preventDefault);
            document.removeEventListener("wheel", preventDefault);
        }

        /**
         * Prevents the default behavior of the specified event by calling the preventDefault method on the event object.
         * @param {Event} e - The event object to prevent the default behavior of.
         */
        function preventDefault(e) {
            e.preventDefault();
        }
    </script>
</body>
</html>