CarRentalService/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.contrib.auth import views as auth_views
from users import views as user_views
from django.conf.urls.static import static
from django.views.generic.base import RedirectView


urlpatterns = [
    path('', user_views.home, name='home'),
    path('admin/', admin.site.urls),
    path('customer/<int:customer_id>/', include('customer.urls')), 
    path('rental/', include('rental.urls')), 
    path('register/', user_views.register, name='register'),
    path('employee/', include('employee.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('manager/', include('manager.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico', permanent=True)),
    path("__reload__/", include("django_browser_reload.urls")), # for auto reloading of the server
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from . import views
import uuid

app_name = 'manager'
urlpatterns = [  
    path('', views.manager, name="manager"),
    path('update_vehicle/<uuid:vehicle_id>', views.updateVehicle, name="update-vehicle"),
    path('create_vehicle', views.createVehicle, name="create-vehicle"),
    path('pay_employees', views.payEmployees, name="pay-employees"),
]

rental/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from employee.models import Vehicle

class VehicleForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ['vehicleYear', 'vehicleMake', 'vehicleModel', 'vehicleImage', 'vehiclePrice', 'vehicleIsRetired']
        
    vehicleYear = forms.IntegerField(
        label='Year',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Year'}),
        required=True
    )
    
    vehicleMake = forms.CharField(
        label='Make',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Make'}),
        max_length=64,
        required=True
    )
    
    vehicleModel = forms.CharField(
        label='Model',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter Model'}),
        max_length=64,
        required=True
    )
    
    vehicleImage = forms.ImageField(
        label='Image',
        # widget=forms.FileInput(attrs={'class': 'form-control-file'}),
        required=True
    )
    
    vehiclePrice = forms.IntegerField(
        label='Price',
        widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter Price'}),
        required=True
    )
    
    vehicleIsRetired = forms.BooleanField(
        label='Is Retired',
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        required=False
    )

manager/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from employee.models import Vehicle
from .forms import VehicleForm


# Create your views here.
def manager(request):
    all_users= get_user_model().objects.all()
    all_vehicles = Vehicle.objects.all()

    
    context= {'allusers': all_users, 'allvehicles': all_vehicles}
    return render(request, 'manager.html', context)

def updateVehicle(request, vehicle_id):
    vehicle = Vehicle.objects.get(vehicleID=vehicle_id)
    form = VehicleForm(request.POST or None, request.FILES or None, instance=vehicle)
    if form.is_valid():
        form.save()
        return redirect('/manager')

    context = {'vehicle': vehicle, 'form': form}
    return render(request, 'updateVehicle.html', context)

def createVehicle(request):
    # vehicle = Vehicle.objects.get(vehicleID=vehicle_id)
    form = VehicleForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/manager')

    context = {'form': form}
    return render(request, 'createVehicle.html', context)

def payEmployees(request):
    all_users= get_user_model().objects.all()
    for user in all_users:
        wage = 15
        hoursWorked = user.profile.hoursWorked
        currentMoney = user.profile.moneyBalance

        moneyToAdd = wage * hoursWorked
        user.profile.moneyBalance = currentMoney + moneyToAdd
        user.profile.hoursWorked = 0
        user.profile.save()
    return redirect('/manager')

manager/templates/createVehicle.html
<!DOCTYPE html>
{% load static %}
{% load static tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Vehicle</title>
    {% tailwind_css %}
</head>
  <body class="bg-secondary text-white-900 flex-col items-center">
      
    <section class="bg-gray-50 dark:bg-gray-900 text-white-900">
      <div
        class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0"
      >
        <div
          class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700"
        >
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1
              class="text-xl font-bold leading-tight tracking-tight text-white-900 md:text-2xl dark:text-white"
            >
              Create New Vehicle:
            </h1> 
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
          
              <table>
                  <tr>
                      <td><label for="{{ form.vehicleYear.id_for_label }}">Year:</label></td>
                      <td><input type="number" name="{{ form.vehicleYear.name }}" id="{{ form.vehicleYear.id_for_label }}"
                        class="bg-gray-50 border border-gray-300 text-white-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter Year" value="{{ form.vehicleYear.value }}" required></td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehicleMake.id_for_label }}">Make:</label></td>
                      <td><input type="text" name="{{ form.vehicleMake.name }}" id="{{ form.vehicleMake.id_for_label }}"
                        class="bg-gray-50 border border-gray-300 text-white-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter Make" maxlength="64" value="{{ form.vehicleMake.value }}" required></td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehicleModel.id_for_label }}">Model:</label></td>
                      <td><input type="text" name="{{ form.vehicleModel.name }}" id="{{ form.vehicleModel.id_for_label }}"
                        class="bg-gray-50 border border-gray-300 text-white-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter Model" maxlength="64" value="{{ form.vehicleModel.value }}" required></td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehicleImage.id_for_label }}">Image:</label></td>
                      <td>
                          <div class="custom-file">
                              <input type="file" name="{{ form.vehicleImage.name }}" id="{{ form.vehicleImage.id_for_label }}"
                                     class="custom-file-input">
                              <label class="custom-file-label" for="{{ form.vehicleImage.id_for_label }}">
                                  {% if form.instance.vehicleImage %}
                                      <a href="{{ form.instance.vehicleImage.url }}" target="_blank">{{ form.instance.vehicleImage.name }}</a>
                                  {% else %}
                                      Choose file...
                                  {% endif %}
                              </label>
                          </div>
                      </td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehiclePrice.id_for_label }}">Price:</label></td>
                      <td><input type="number" name="{{ form.vehiclePrice.name }}" id="{{ form.vehiclePrice.id_for_label }}"
                        class="bg-gray-50 border border-gray-300 text-white-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter Price" value="{{ form.vehiclePrice.value }}" required></td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehicleIsRetired.id_for_label }}">Is Retired:</label></td>
                      <td>
                          <div class="form-check">
                              <input type="checkbox" name="{{ form.vehicleIsRetired.name }}" id="{{ form.vehicleIsRetired.id_for_label }}"
                                     class="form-check-input" {% if form.vehicleIsRetired.value %}checked{% endif %}>
                              <label class="form-check-label" for="{{ form.vehicleIsRetired.id_for_label }}">Is Retired:</label>
                          </div>
                      </td>
                  </tr>
              </table>
          
              <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Save</button>
          </form>
          </div>
        </div>
      </div>
    </section>

    <p></p>
  </body>
</html>

manager/templates/manager.html
<!DOCTYPE html>
{% load static %} {% load static tailwind_tags %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Manager Page</title>
    {% tailwind_css %}
  </head>

  <body class="bg-secondary text-white-900 flex-col items-center">
    <section>
      <div
        class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0"
      >
        <div
          class="bg-white rounded-lg shadow dark:border md:mt-0 dark:bg-gray-800 dark:border-gray-700"
        >
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1
              class="text-xl font-bold leading-tight tracking-tight text-white-900 md:text-2xl dark:text-white"
            >
              Manager Page
            </h1>

            <h1
              class="text-lg font-bold leading-tight tracking-tight text-white-900 dark:text-white"
            >
              User Information:
            </h1>

            <p>Current wage: $15/hr</p>

            <button
              class="bg-purple-900 hover:bg-purple-700 w-52 h-10 mt-5 rounded-md font-semibold"
            >
              <a href="{% url 'manager:pay-employees' %}">Pay Employees</a>
            </button>

            <table>
              <tr>
                <th style="width: 150px; text-align: left">Username</th>
                <th style="width: 150px; text-align: left">Hours worked</th>
                <th style="width: 150px; text-align: left">Money balance</th>
              </tr>

              {% for User in allusers %}
              <tr>
                <td>{{ User}}</td>
                <td>{{ User.profile.hoursWorked}}</td>
                <td>{{ User.profile.moneyBalance}}</td>
              </tr>
              {% endfor %}
            </table>

            <h1
              class="text-lg font-bold leading-tight tracking-tight text-white-900 dark:text-white"
            >
              Vehicle Information:
            </h1>

            <button
              class="bg-purple-900 hover:bg-purple-700 w-52 h-10 mt-5 rounded-md font-semibold"
            >
              <a href="{% url 'manager:create-vehicle' %}"
                >Create New Vehicle</a
              >
            </button>

            <table class="table-fixed">
              <tr>
                <th style="width: 250px; text-align: left">Vehicle</th>
                <th style="width: 100px; text-align: left">Year</th>
                <th style="width: 100px; text-align: left">Renting Price</th>
                <th style="width: 100px; text-align: left">Is retired?</th>
                <th style="width: 200px; text-align: left">Update</th>
              </tr>

              {% for Vehicle in allvehicles %}
              <tr>
                <td>{{ Vehicle.vehicleMake}} {{ Vehicle.vehicleModel}}</td>
                <td>{{ Vehicle.vehicleYear}}</td>
                <td>${{ Vehicle.vehiclePrice}}</td>
                <td>{{ Vehicle.vehicleIsRetired}}</td>
                <td>
                  <a href="{% url 'manager:update-vehicle' Vehicle.vehicleID %}"
                    >Click to update</a
                  >
                </td>
              </tr>

              {% endfor %}
            </table>

            <button
              onclick="location.href = '/'"
              class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
            >
              Click to return home
            </button>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

manager/templates/updateVehicle.html
<!DOCTYPE html>
{% load static %}
{% load static tailwind_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Vehicle</title>
    {% tailwind_css %}
</head>
  <body class="bg-secondary text-white-900 flex-col items-center">   

    <section class="bg-gray-50 dark:bg-gray-900 text-white-900">
      <div
        class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0"
      >
        <div
          class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700"
        >
          <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <h1
              class="text-xl font-bold leading-tight tracking-tight text-white-900 md:text-2xl dark:text-white"
            >
              Update Vehicle:
            </h1> 
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
          
              <table>
                  <tr>
                      <td><label for="{{ form.vehicleYear.id_for_label }}">Year:</label></td>
                      <td><input type="number" name="{{ form.vehicleYear.name }}" id="{{ form.vehicleYear.id_for_label }}"
                        class="bg-gray-50 border border-gray-300 text-white-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter Year" value="{{ form.vehicleYear.value }}" required></td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehicleMake.id_for_label }}">Make:</label></td>
                      <td><input type="text" name="{{ form.vehicleMake.name }}" id="{{ form.vehicleMake.id_for_label }}"
                        class="bg-gray-50 border border-gray-300 text-white-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter Make" maxlength="64" value="{{ form.vehicleMake.value }}" required></td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehicleModel.id_for_label }}">Model:</label></td>
                      <td><input type="text" name="{{ form.vehicleModel.name }}" id="{{ form.vehicleModel.id_for_label }}"
                        class="bg-gray-50 border border-gray-300 text-white-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter Model" maxlength="64" value="{{ form.vehicleModel.value }}" required></td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehicleImage.id_for_label }}">Image:</label></td>
                      <td>
                          <div class="custom-file">
                              <input type="file" name="{{ form.vehicleImage.name }}" id="{{ form.vehicleImage.id_for_label }}"
                                     class="custom-file-input">
                              <label class="custom-file-label" for="{{ form.vehicleImage.id_for_label }}">
                                  {% if form.instance.vehicleImage %}
                                      <a href="{{ form.instance.vehicleImage.url }}" target="_blank">{{ form.instance.vehicleImage.name }}</a>
                                  {% else %}
                                      Choose file...
                                  {% endif %}
                              </label>
                          </div>
                      </td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehiclePrice.id_for_label }}">Price:</label></td>
                      <td><input type="number" name="{{ form.vehiclePrice.name }}" id="{{ form.vehiclePrice.id_for_label }}"
                        class="bg-gray-50 border border-gray-300 text-white-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Enter Price" value="{{ form.vehiclePrice.value }}" required></td>
                  </tr>
                  <tr>
                      <td><label for="{{ form.vehicleIsRetired.id_for_label }}">Is Retired:</label></td>
                      <td>
                          <div class="form-check">
                              <input type="checkbox" name="{{ form.vehicleIsRetired.name }}" id="{{ form.vehicleIsRetired.id_for_label }}"
                                     class="form-check-input" {% if form.vehicleIsRetired.value %}checked{% endif %}>
                              <label class="form-check-label" for="{{ form.vehicleIsRetired.id_for_label }}">Is Retired:</label>
                          </div>
                      </td>
                  </tr>
              </table>
          
              <button type="submit" class="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800">Save</button>
          </form>
          </div>
        </div>
      </div>
    </section>

    <p></p>
  </body>
</html>